version: '3'
services:
  student1:
    image: student
    container_name: student1
    networks:
      - my_network

  student2:
    image: student
    container_name: student2
    networks:
      - my_network

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
